# Generated by Django 3.2.5 on 2021-07-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('introduction', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=255)),
                ('correct', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('raw', models.JSONField()),
                ('average_response_time', models.PositiveIntegerField()),
                ('fastest_response_time', models.PositiveIntegerField()),
                ('slowest_response_time', models.PositiveIntegerField()),
                ('median_response_time', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive_skills.test')),
            ],
        ),
    ]
