# Generated by Django 3.2.5 on 2021-08-02 00:46

from django.db import migrations, models
import django.db.models.deletion
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='test',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cognitive_skills.test'),
        ),
    ]
