# Generated by Django 3.2.5 on 2021-08-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0002_auto_20210802_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='test',
            name='sort_order',
        ),
    ]
