# Generated by Django 3.2.5 on 2021-08-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0004_auto_20210802_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='average_response_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='fastest_response_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='median_response_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='slowest_response_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
