# Generated by Django 3.2.5 on 2021-08-22 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0006_load_initial_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turk_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='result',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='cognitive_skills.worker'),
            preserve_default=False,
        ),
    ]
