# Generated by Django 3.2.5 on 2021-09-10 06:47

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0007_auto_20210822_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, help_text='You must be 18+ to take this survey'),
        ),
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='education',
            field=models.CharField(choices=[('none', 'None'), ('grade_school', 'Grade School (Preschool to 8th Grade)'), ('some_high_school', 'Some High School, No Diploma'), ('high_school', 'High School Graduate, Diploma or equivalent (GED)'), ('some_college', 'Some College Credit, No Degree'), ('trade', 'Trade/Vocational School'), ('associates_degree', 'Associates Degree'), ('bachelors_degree', 'Bachelor’s Degree'), ('masters_degree', 'Master’s Degree'), ('some_postgraduate', 'Some Postgraduate Work, No Degree'), ('postgraduate', 'Ph.D., J.D., M.D., or Other Professional Degree')], default='none', help_text='What is the highest degree or level of education you have completed?', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment',
            field=models.CharField(choices=[('employed', 'Employed for wages'), ('self_employed', 'Self Employed'), ('unemployed_looking', 'Out of work and looking for work'), ('unemployed_not_looking', 'Out of work but not currently looking for work'), ('homemaker', 'Homemaker'), ('student', 'Student'), ('military', 'Active-Duty Military'), ('veteran', 'Veteran'), ('retired', 'Retired'), ('disabled', 'Unable to work')], default='employed', help_text='Please select your current employment status.', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='ethnicity',
            field=models.CharField(choices=[('black', 'African, African American, Black'), ('indigenous', 'American Indian, Alaska Native'), ('asian', 'Asian, Asian-American'), ('hispanic', 'Hispanic, Latino, Latina, LatinX'), ('middle_eastern', 'Middle Eastern'), ('pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('white', 'Non-Hispanic Caucasian, White')], default='white', help_text='Which of the following ethnic group(s) do you consider yourself a member?', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender_male', 'Transgender Male'), ('transgender_female', 'Transgender Female'), ('gender_nonconforming', 'Gender Variant/Non-Conforming'), ('prefer_not_to_answer', 'Prefer Not To Answer')], default='prefer_not_to_answer', help_text='To which gender identity do you most identify?', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='marital_status',
            field=models.CharField(choices=[('single_never_married', 'Single, Never Married'), ('single_previously_married', 'Single, Previously Married'), ('married', 'Married'), ('domestic_partnership', 'Domestic Partnership'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single_never_married', help_text='What is your marital status?', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='orientation',
            field=models.CharField(choices=[('heterosexual', 'Heterosexual'), ('gay', 'Gay'), ('lesbian', 'Lesbian'), ('bisexual', 'Bisexual'), ('other', 'Other')], default='other', help_text='Which of the following do you most strongly identify with?', max_length=255),
        ),
        migrations.AddField(
            model_name='worker',
            name='state',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='turk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
