# Generated by Django 3.2.5 on 2021-09-15 22:38
from django.utils import timezone
from django.db import migrations

def fill_created_modified_fields(apps, schema_editor):
    Result = apps.get_model('cognitive_skills', 'Result')
    Test = apps.get_model('cognitive_skills', 'Test')
    Worker = apps.get_model('cognitive_skills', 'Worker')

    for result in Result.objects.all():
        result.created_at = timezone.now()
        result.updated_at = timezone.now()
        result.save()
    
    for test in Test.objects.all():
        test.created_at = timezone.now()
        test.updated_at = timezone.now()
        test.save()
    
    for worker in Worker.objects.all():
        worker.created_at = timezone.now()
        worker.updated_at = timezone.now()
        worker.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0011_auto_20210915_2238'),
    ]

    operations = [
        migrations.RunPython(fill_created_modified_fields)
    ]
