# Generated by Django 3.2.5 on 2022-12-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0014_auto_20210915_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
