# Generated by Django 3.2.5 on 2022-12-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0015_alter_worker_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='years_of_education',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, help_text='How many years of education have you received?', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('grade_school', 'Grade School (Preschool to 8th Grade)'), ('some_high_school', 'Some High School, No Diploma'), ('high_school', 'High School Graduate, Diploma or equivalent (GED)'), ('some_college', 'Some College Credit, No Degree'), ('trade', 'Trade/Vocational School'), ('associates_degree', 'Associates Degree'), ('bachelors_degree', 'Bachelor’s Degree'), ('masters_degree', 'Master’s Degree'), ('some_postgraduate', 'Some Postgraduate Work, No Degree'), ('postgraduate', 'Ph.D., J.D., M.D., or Other Professional Degree')], help_text='What is the highest degree or level of education you have completed?', max_length=255, null=True),
        ),
    ]
