# Generated by Django 3.2.5 on 2023-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_skills', '0018_alter_worker_years_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='years_of_education',
            field=models.PositiveSmallIntegerField(help_text='How many years of education have you received?'),
        ),
    ]
